//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotRas.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotRas.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} contained a non-interactive flag, however the authentication protocol  must display a UI to obtain the required identity information..
        /// </summary>
        internal static string Argument_EapOptionsRequireInteractiveMode {
            get {
                return ResourceManager.GetString("Argument_EapOptionsRequireInteractiveMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone number cannot be an empty string if the entry name has not been provided..
        /// </summary>
        internal static string Argument_EmptyEntryNameAndPhoneNumber {
            get {
                return ResourceManager.GetString("Argument_EmptyEntryNameAndPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; already exists in the phone book..
        /// </summary>
        internal static string Argument_EntryAlreadyExists {
            get {
                return ResourceManager.GetString("Argument_EntryAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} contains an incorrect address family..
        /// </summary>
        internal static string Argument_IncorrectAddressFamily {
            get {
                return ResourceManager.GetString("Argument_IncorrectAddressFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} &apos;{1}&apos; is invalid. Ensure the entry does not already exist in the phone book, and does not contain invalid characters..
        /// </summary>
        internal static string Argument_InvalidEntryName {
            get {
                return ResourceManager.GetString("Argument_InvalidEntryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; contains an invalid file name..
        /// </summary>
        internal static string Argument_InvalidFileName {
            get {
                return ResourceManager.GetString("Argument_InvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; was not a valid handle..
        /// </summary>
        internal static string Argument_InvalidHandle {
            get {
                return ResourceManager.GetString("Argument_InvalidHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must have the PhoneNumber, DeviceType, DeviceName, FramingProtocol, and EntryType properties set as a minimum..
        /// </summary>
        internal static string Argument_MissingRequiredInfo {
            get {
                return ResourceManager.GetString("Argument_MissingRequiredInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; cannot be a null reference or empty string..
        /// </summary>
        internal static string Argument_StringCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("Argument_StringCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than zero..
        /// </summary>
        internal static string Argument_ValueCannotBeLessThanOrEqualToZero {
            get {
                return ResourceManager.GetString("Argument_ValueCannotBeLessThanOrEqualToZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be less than zero..
        /// </summary>
        internal static string Argument_ValueCannotBeLessThanZero {
            get {
                return ResourceManager.GetString("Argument_ValueCannotBeLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; specified is longer than the string..
        /// </summary>
        internal static string Argument_ValueLongerThanString {
            get {
                return ResourceManager.GetString("Argument_ValueLongerThanString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior.
        /// </summary>
        internal static string CatBehavior {
            get {
                return ResourceManager.GetString("CatBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string CatData {
            get {
                return ResourceManager.GetString("CatData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        internal static string CatLayout {
            get {
                return ResourceManager.GetString("CatLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the phone book entry to modify..
        /// </summary>
        internal static string EPBEDEntryNameDesc {
            get {
                return ResourceManager.GetString("EPBEDEntryNameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The caller does not have the required permission to perform the action requested..
        /// </summary>
        internal static string Exception_AccessDeniedBySecurity {
            get {
                return ResourceManager.GetString("Exception_AccessDeniedBySecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entry is not associated with a phone book..
        /// </summary>
        internal static string Exception_EntryNotInPhoneBook {
            get {
                return ResourceManager.GetString("Exception_EntryNotInPhoneBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The handle is not network access protection (NAP) capable..
        /// </summary>
        internal static string Exception_HandleNotNapCapable {
            get {
                return ResourceManager.GetString("Exception_HandleNotNapCapable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The handle is invalid or closed..
        /// </summary>
        internal static string Exception_InvalidOrClosedHandle {
            get {
                return ResourceManager.GetString("Exception_InvalidOrClosedHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported on the current platform..
        /// </summary>
        internal static string Exception_NotSupportedOnPlatform {
            get {
                return ResourceManager.GetString("Exception_NotSupportedOnPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation has timed out..
        /// </summary>
        internal static string Exception_OperationTimedOut {
            get {
                return ResourceManager.GetString("Exception_OperationTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone book is corrupted or missing components..
        /// </summary>
        internal static string Exception_PhonebookCorrupted {
            get {
                return ResourceManager.GetString("Exception_PhonebookCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone book must be opened prior to performing this operation..
        /// </summary>
        internal static string Exception_PhoneBookNotOpened {
            get {
                return ResourceManager.GetString("Exception_PhoneBookNotOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone number or entry name is required to dial an entry..
        /// </summary>
        internal static string Exception_PhoneNumberOrEntryNameRequired {
            get {
                return ResourceManager.GetString("Exception_PhoneNumberOrEntryNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of the object returned was not expected..
        /// </summary>
        internal static string Exception_UnexpectedSizeReturned {
            get {
                return ResourceManager.GetString("Exception_UnexpectedSizeReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items within the collection cannot be set directly..
        /// </summary>
        internal static string NotSupported_ItemsCannotBeSet {
            get {
                return ResourceManager.GetString("NotSupported_ItemsCannotBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Book Files (*.pbk)|*.pbk|All Files (*.*)|*.*.
        /// </summary>
        internal static string PhoneBookFileFilter {
            get {
                return ResourceManager.GetString("PhoneBookFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of time (in seconds) before the connection attempt is aborted..
        /// </summary>
        internal static string RADMConnectionQueryTimeoutDesc {
            get {
                return ResourceManager.GetString("RADMConnectionQueryTimeoutDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates whether AutoDial displays a dialog box to query the user before creating a connection..
        /// </summary>
        internal static string RADMDisableConnectionQueryDesc {
            get {
                return ResourceManager.GetString("RADMDisableConnectionQueryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of time (in seconds) between AutoDial connection attempts..
        /// </summary>
        internal static string RADMFailedConnectionTimeoutDesc {
            get {
                return ResourceManager.GetString("RADMFailedConnectionTimeoutDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates whether the system disables all AutoDial connections for the current session..
        /// </summary>
        internal static string RADMLogOnSessionDisableDesc {
            get {
                return ResourceManager.GetString("RADMLogOnSessionDisableDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of addresses that AutoDial stores in the registry..
        /// </summary>
        internal static string RADMSavedAddressesLimitDesc {
            get {
                return ResourceManager.GetString("RADMSavedAddressesLimitDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the dialog has encountered an error..
        /// </summary>
        internal static string RCDErrorDesc {
            get {
                return ResourceManager.GetString("RCDErrorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The coordinates of the upper-left corner of the dialog box..
        /// </summary>
        internal static string RCDLocationDesc {
            get {
                return ResourceManager.GetString("RCDLocationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object used to marshal event-handler calls..
        /// </summary>
        internal static string RCSyncObjectDesc {
            get {
                return ResourceManager.GetString("RCSyncObjectDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when a remote access connection subentry has connected..
        /// </summary>
        internal static string RCWBandwidthAddedDesc {
            get {
                return ResourceManager.GetString("RCWBandwidthAddedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when a remote access connection subentry has disconnected..
        /// </summary>
        internal static string RCWBandwidthRemovedDesc {
            get {
                return ResourceManager.GetString("RCWBandwidthRemovedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when a remote access connection is established..
        /// </summary>
        internal static string RCWConnectedDesc {
            get {
                return ResourceManager.GetString("RCWConnectedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when a remote access connection is disconnected..
        /// </summary>
        internal static string RCWDisconnectedDesc {
            get {
                return ResourceManager.GetString("RCWDisconnectedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates whether the component will be enabled..
        /// </summary>
        internal static string RCWEnableRaisingEventsDesc {
            get {
                return ResourceManager.GetString("RCWEnableRaisingEventsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The callback number for the remote server to dial..
        /// </summary>
        internal static string RDCallbackNumberDesc {
            get {
                return ResourceManager.GetString("RDCallbackNumberDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the asynchronous dial operation has completed..
        /// </summary>
        internal static string RDDialCompletedDesc {
            get {
                return ResourceManager.GetString("RDDialCompletedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone number to dial (overriding the entry phone number)..
        /// </summary>
        internal static string RDDPhoneNumberDesc {
            get {
                return ResourceManager.GetString("RDDPhoneNumberDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The extensible authentication protocol (EAP) options..
        /// </summary>
        internal static string RDEapOptionsDesc {
            get {
                return ResourceManager.GetString("RDEapOptionsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entry options..
        /// </summary>
        internal static string RDEntryOptionsDesc {
            get {
                return ResourceManager.GetString("RDEntryOptionsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parent window used for dialog box creation and centering..
        /// </summary>
        internal static string RDOwnerDesc {
            get {
                return ResourceManager.GetString("RDOwnerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The full path (including file name) of the phone book..
        /// </summary>
        internal static string RDPhoneBookPathDesc {
            get {
                return ResourceManager.GetString("RDPhoneBookPathDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the connection state changes..
        /// </summary>
        internal static string RDStateChangedDesc {
            get {
                return ResourceManager.GetString("RDStateChangedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The zero-based index of the subentry to dial..
        /// </summary>
        internal static string RDSubEntryIdDesc {
            get {
                return ResourceManager.GetString("RDSubEntryIdDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of time (in milliseconds) until the asynchronous connection attempt times out..
        /// </summary>
        internal static string RDTimeoutDesc {
            get {
                return ResourceManager.GetString("RDTimeoutDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the entry..
        /// </summary>
        internal static string REDEntryNameDesc {
            get {
                return ResourceManager.GetString("REDEntryNameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates whether entries cannot be renamed while in edit mode..
        /// </summary>
        internal static string REDNoRenameDesc {
            get {
                return ResourceManager.GetString("REDNoRenameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The full path (including file name) of the phone book to modify..
        /// </summary>
        internal static string REDPhoneBookPathDesc {
            get {
                return ResourceManager.GetString("REDPhoneBookPathDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone number to dial..
        /// </summary>
        internal static string REDPhoneNumberDesc {
            get {
                return ResourceManager.GetString("REDPhoneNumberDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The style of dialog box to display..
        /// </summary>
        internal static string REDRasDialogStyleDesc {
            get {
                return ResourceManager.GetString("REDRasDialogStyleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the phone book has changed..
        /// </summary>
        internal static string RPBChangedDesc {
            get {
                return ResourceManager.GetString("RPBChangedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the user creates a new entry or copies an existing entry..
        /// </summary>
        internal static string RPBDAddedEntryDesc {
            get {
                return ResourceManager.GetString("RPBDAddedEntryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the user changes an existing phone book entry..
        /// </summary>
        internal static string RPBDChangedEntryDesc {
            get {
                return ResourceManager.GetString("RPBDChangedEntryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the user successfully dials an entry..
        /// </summary>
        internal static string RPBDDialedEntryDesc {
            get {
                return ResourceManager.GetString("RPBDDialedEntryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the phone book has been deleted..
        /// </summary>
        internal static string RPBDeletedDesc {
            get {
                return ResourceManager.GetString("RPBDeletedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the entry to initially highlight..
        /// </summary>
        internal static string RPBDEntryNameDesc {
            get {
                return ResourceManager.GetString("RPBDEntryNameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the user removes a phone book entry..
        /// </summary>
        internal static string RPBDRemovedEntryDesc {
            get {
                return ResourceManager.GetString("RPBDRemovedEntryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates whether the phone book file will be monitored for external changes..
        /// </summary>
        internal static string RPBEnableFileWatcherDesc {
            get {
                return ResourceManager.GetString("RPBEnableFileWatcherDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the phone book has been renamed..
        /// </summary>
        internal static string RPBRenamedDesc {
            get {
                return ResourceManager.GetString("RPBRenamedDesc", resourceCulture);
            }
        }
    }
}
